### ISSUE TITLE
Exception when showing Gantt Chart on Postgresql DB (Heroku)

### ISSUE THREAD

**Issue by hussam789** [fguillot/kanboard#1146]
i'm running the latest Dev. Version o kanboard on Heroku with Postgresql DB: 
```
Uncaught exception 'PicoDb\SQLException' with message 'SQL error' in /app/vendor/fguillot/picodb/lib/PicoDb/Database.php:319
#0 /app/vendor/fguillot/picodb/lib/PicoDb/Database.php(276): PicoDb\Database->handleSqlError(Object(PDOException))
#1 /app/vendor/fguillot/picodb/lib/PicoDb/Table.php(274): PicoDb\Database->execute('SELECT (SELECT ...', Array)
#2 /app/app/Model/TaskFilter.php(688): PicoDb\Table->findAll()
#3 /app/app/Controller/Gantt.php(73): Model\TaskFilter->toGanttBars()
```

**Comment by fguillot** [comment]
It's now fixed.

Thanks
