### ISSUE TITLE
Bug on subtask list

### ISSUE THREAD

**Issue by AlgyTaylor** [fguillot/kanboard#750]
When I try to move the 7th subtask up to 6th position in a subtask list, I get a nasty PHP error on the dev version:
```
Notice: Undefined offset: 7 in E:\webs\kanban\app\Model\Subtask.php on line 274

Notice: Undefined index: in E:\webs\kanban\app\Model\Subtask.php on line 274

Notice: Undefined offset: 7 in E:\WebServer\kanban\app\Model\Subtask.php on line 278

Notice: Undefined offset: 7 in E:\webs\kanban\app\Model\Subtask.php on line 278

Fatal error: Uncaught exception 'RuntimeException' with message 'SQL error' in E:\webs\kanban\vendor\fguillot\picodb\lib\PicoDb\Database.php:251 Stack trace: #0 E:\webs\kanban\vendor\fguillot\picodb\lib\PicoDb\Table.php(94): PicoDb\Database->execute('UPDATE "subtask...', Array) #1 E:\webs\kanban\app\Model\Subtask.php(278): PicoDb\Table->update(Array) #2 E:\webs\kanban\app\Controller\Subtask.php(277): Model\Subtask->moveUp(1, 47) #3 E:\webs\kanban\app\Core\Router.php(88): Controller\Subtask->movePosition() #4 E:\webs\kanban\app\Core\Router.php(107): Core\Router->load('E:\\webs\\ka...', '\\Controller\\sub...', 'moveposition') #5 E:\webs\kanban\index.php(9): Core\Router->execute() #6 {main} thrown in E:\webs\kanban\vendor\fguillot\picodb\lib\PicoDb\Database.php on line 251
```

If it's any use, the path I'm viewing is:
http://server/?controller=task&action=show&task_id=1&project_id=2

and the tasklist had id6 - assigned, 8hrs/20 complete
id7 - not assigned, no work

**Comment by fguillot** [comment]
Can you enable the debug mode and copy the sql error here?

Add `define('DEBUG', true);` to the file config.php, that enable debug output to `data/debug.log`

**Comment by AlgyTaylor** [comment]
I've come in to the same error again ...

```
Notice: Undefined offset: 4 in E:\webs\kanban\app\Model\Subtask.phpon line 246

Notice: Undefined index: in E:\webs\kanban\app\Model\Subtask.phpon line 246

Notice: Undefined offset: 4 in E:\webs\kanban\app\Model\Subtask.php on line 250

Notice: Undefined offset: 4 in E:\webs\kanban\app\Model\Subtask.php on line 250

Fatal error: Uncaught exception 'RuntimeException' with message 'SQL error: SQLSTATE[08P01]: <<Unknown error>>: 7 ERROR: bind message supplies 1 parameters, but prepared statement "pdo_stmt_00000008" requires 2' in E:\webs\kanban\vendor\fguillot\picodb\lib\PicoDb\Database.php:251 Stack trace: #0 E:\webs\kanban\vendor\fguillot\picodb\lib\PicoDb\Table.php(94): PicoDb\Database->execute('UPDATE "subtask...', Array) #1 E:\webs\kanban\app\Model\Subtask.php(250): PicoDb\Table->update(Array) #2 E:\webs\kanban\app\Controller\Subtask.php(277): Model\Subtask->moveDown(210, 91) #3 E:\webs\kanban\app\Core\Router.php(88): Controller\Subtask->movePosition() #4 E:\webs\kanban\app\Core\Router.php(107): Core\Router->load('E:\\webs\\ka...', '\\Controller\\sub...', 'moveposition') #5 E:\webs\kanban\index.php(9): Core\Router->execute() #6 {main} thrown in E:\webs\kanban\vendor\fguillot\picodb\lib\PicoDb\Database.php on line 251
```

It's happened after I'd renamed a subtask that had already had some time allocated to it, in the middle of a list of subtasks (there's 2 above, 2 below). The above is the output with debug set to true :)

**Comment by fguillot** [comment]
Do you have the sql query in your `debug.log` file?

**Comment by fguillot** [comment]
Finally I found the bug, it happen when you delete a subtask and change the position after that.

It's fixed in the master branch.
